export const ACTION_CATEGORY="ACTION_CATEGORY";
export const ACTION_DIFFICULTY="ACTION_DIFFICULTY";
export const ACTION_TYPE="ACTION_TYPEY";
export const ACTION_MOUNT="ACTION_MOUNT";
export const ACTION_SCORE="ACTION_SCORE";