export const INCREMENT="INCREMENT";
export const DECREMENT="DECREMENT";
export const INCREMENT_BY_VALUE="INCREMENT_BY_VALUE";
export const FETCH_USER="FETCH_USER";
export const FETCH_START="FETCH_START";
export const DELETEPRODUCT="|DELETE-PRODUCT";
export const ADDPRODUCT="ADD-PRODUCT";
export const FILTERPRODUCT="FILTERPRODUCT";